name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4.1.1
    - name: Cypress.io
      uses: cypress-io/github-action@v6.5.0
      with: 
        start: npm start

  - name: Set up Node.js
      uses: actions/setup-node@v16.15.1
      with:
        node-version: v16.15.1

    - name: Install dependencies
      run: npm install

    - name: Start the application (if needed)
      run: npm start # Change this to your application's start command

    - name: Run Cypress tests
      run: npx cypress run
